#!/bin/bash


zcat  \
    | python <(cat <<EOF
from itertools import combinations
import csv
import pandas as pd
import numpy as np
import re
x =[]
with open('MCT_INPUT', 'r' ) as d:
        keeper = "00"  
        for row in csv.reader(d ,dialect="excel-tab"):
            if row[0] != keeper: #if want to select just one sample remove two lines and set keeper to questioned sample
                keeper = row[0]
            if row[0] == keeper:
                x = np.append (x, [row[1]])
count = 0
for each in combinations(x,2):
    t = ':'.join(each)
    y = t.split(':')
    if y[0] == y[5]:  #this is for cis only cool generation. if inter is also needed remove this line and shift-tab below two
        temp = int(y[4])*int(y[9])
        print(y[0] , y[1] , y[5] , y[6], str(temp) ,sep='\t')
    count +=1

EOF
)  \
   | cooler cload pairs \
        -c1 1 -p1 2 -c2 3 -p2 4 \
        --zero-based --chunksize 10000000 --field count=5:dtype=float32 \
        CHROMSIZE:25000 - "OUTPUT.cool"
